### PR TITLE
Bump cluster-standup-teardown to v1.27.3 to update CAPV cluster values for the new vSphere provider

### PR DESCRIPTION
**Pull request by glitchcrab**
### What this PR does

towards https://github.com/giantswarm/giantswarm/issues/32054

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by glitchcrab** [comment]
let's re-run the fun

/run cluster-test-suites TARGET_SUITES=./providers/capv/standard

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/standard

**Comment by glitchcrab** [comment]
last try for tonight 

/run cluster-test-suites TARGET_SUITES=./providers/capv/standard

**Review by Gacko — APPROVED** [review]

**Comment by vxav** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/standard

**Comment by glitchcrab** [comment]
the e2e tests will fail because we need [a new Release](https://github.com/giantswarm/releases/pull/1497) to fix issues with kube-vip. I'm going to merge this PR as the changes have been tested locally.

**Pull request merged**
