### PR TITLE
Use custom dialer for hello-world call

### PR DESCRIPTION
**Pull request by AverageMarcus**
### What this PR does

Implements a custom dialer for the HTTP client to perform the DNS lookup in code rather than relying on the host system. This should (hopefully) mean that the initial Not Found results aren't cached as the DNS nameserver is actually checked each time for the result. This should hopefully cut down on the flakey-ness of the hello-world test that fails because the domain doesn't resolve quick enough.

Fixes: https://github.com/giantswarm/giantswarm/issues/29469

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Looks like something isn't right with the code, it seems to still be using CoreDNS for the lookup:
```
The function passed to Eventually returned the following error:
      <*url.Error | 0xc0008f1680>: 
      Get "https://hello-world.t-ryvh392ms5cgo36z6g.gaws.gigantic.io/": dial tcp: lookup [hello-world.t-ryvh392ms5cgo36z6g.gaws.gigantic.io](http://hello-world.t-ryvh392ms5cgo36z6g.gaws.gigantic.io/) on 172.31.0.10:53: server misbehaving
      {
          Op: "Get",
          URL: "https://hello-world.t-ryvh392ms5cgo36z6g.gaws.gigantic.io/",
          Err: <*net.OpError | 0xc0003c9680>{
              Op: "dial",
              Net: "tcp",
              Source: nil,
              Addr: nil,
              Err: <*net.DNSError | 0xc000377780>{
                  Err: "server misbehaving",
                  Name: "[hello-world.t-ryvh392ms5cgo36z6g.gaws.gigantic.io](http://hello-world.t-ryvh392ms5cgo36z6g.gaws.gigantic.io/)",
                  Server: "172.31.0.10:53",
                  IsTimeout: false,
                  IsTemporary: true,
                  IsNotFound: false,
              },
          },
      }
```

**Review by yulianedyalkova — APPROVED** [review]
Happy once the tests are green.

**Comment by AverageMarcus** [comment]
This is currently blocked by https://github.com/giantswarm/giantswarm/issues/29508

**Pull request merged**
