### PR TITLE
Use max node pool name length

### PR DESCRIPTION
**Pull request by fiunchinho**
### What this PR does
Towards https://github.com/giantswarm/giantswarm/issues/29041

### Checklist

- [X] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by fiunchinho** [comment]
All tests passed but `eks`. I'm re-running again to take a look.
/run cluster-test-suites

**Comment by fiunchinho** [comment]
Blocked until this is released https://github.com/giantswarm/cluster-eks/pull/51

**Review by calvix — APPROVED** [review]

**Pull request merged**
