### PR TITLE
capvcd 1.25.13

### PR DESCRIPTION
**Pull request by vxav**
### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by glitchcrab** [comment]
do we not want to drop the values here to consume the defaults from the cluster chart?

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Also while I think about it, Ubuntu 20.04 is a bit dated now isn't it? Any reason not to use 22.04 until ignition is supported in CAPVCD?

**Comment by vxav** [comment]
If we don't get a decision on the nodeClass thing I'll just set the default values in the less ideal way but it is planned yes.

Regarding 20.04 I did try 22.04 a long time ago and I had lots of issues with cgroups with CAPVCD. However Flatcar is around the corner (PR merged upstream).

**Comment by AverageMarcus** [comment]
> However Flatcar is around the corner (PR merged upstream).

Yay! 

Does that mean we need to add CAPVCD support for capi-image-builder? Or does it use the same as CAPV?

**Comment by vxav** [comment]
We can use the same as CAPV.

**Pull request merged**
