### PR TITLE
Set specific awsClusterRoleIdentityName for CAPA test suites

### PR DESCRIPTION
**Pull request by ericgraf**
### What this PR does

Towards: https://github.com/giantswarm/giantswarm/issues/29815

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by Gacko — APPROVED** [review]

**Comment by AverageMarcus** [comment]
🤦  This is going to fail.

**Comment by AverageMarcus** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa,./providers/eks

**Comment by AverageMarcus** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/private,./providers/capa/cilium-eni-mode

**Comment by AverageMarcus** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/private

**Comment by AverageMarcus** [comment]
COME ON!!!! 😞 

/run cluster-test-suites TARGET_SUITES=./providers/capa/private

**Comment by AverageMarcus** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/private

**Comment by fiunchinho** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/private

**Comment by fiunchinho** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/private

**Comment by AverageMarcus** [comment]
It looks like the private CAPA WCs don't currently work when deployed into a different AWS account. I've opened an issue for Team Phoenix to investigate and will be removing the change for private WCs from this PR so we can at least have the others isolated.

Issue: https://github.com/giantswarm/roadmap/issues/3671

**Comment by AverageMarcus** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa,./providers/eks

**Comment by AverageMarcus** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/cilium-eni-mode

**Pull request merged**
