### PR TITLE
Bump to Go v1.23 and update deps to match

### PR DESCRIPTION
**Pull request by AverageMarcus**
### What this PR does

Towards: https://github.com/giantswarm/giantswarm/issues/31630

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]

**Review by Gacko — APPROVED** [review]

**Comment by Gacko** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/cilium-eni-mode

**Comment by AverageMarcus** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/cilium-eni-mode

**Comment by AverageMarcus** [comment]
Re-running after fixing conflicts

/run cluster-test-suites

**Comment by AverageMarcus** [comment]
Lets try that again...

/run cluster-test-suites

**Comment by AverageMarcus** [comment]
Failures are flakes and enough test suites are passing that I'm confident in this change so I'm adding the skip label

**Pull request merged**
