### PR TITLE
Update clustertest to v0.8.0

### PR DESCRIPTION
**Pull request by fiunchinho**
### What this PR does
Update to latest `clustertest` release.

### Checklist

- [X] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Sorry, I needed to manually cancel the in-progress test run. Re-triggering...


/run cluster-test-suites

**Comment by fiunchinho** [comment]
I updated the branch, but I didn't trigger again.

**Comment by AverageMarcus** [comment]
> I updated the branch, but I didn't trigger again.

New commits or similar don't automatically re-trigger the tests, you need to use the comment triggers.

**Comment by fiunchinho** [comment]
Yeah I know, I wanted to wanr you about that if you don't see the link to the github check/status for the tests is because I updated the branch so the status is gone from the box, only the `Heimdall` one is remaining.

**Comment by AverageMarcus** [comment]
Ah, gotcha! Nota big deal. I mostly just wanted to make sure the tests were working again so I'd be happy to have this merged in with the skip label if needed.

**Comment by fiunchinho** [comment]
How do we apply the label again? Just using github UI?

**Comment by AverageMarcus** [comment]
Yeah, just add it over on the right. We don't have any slash commands for it.

**Comment by fiunchinho** [comment]
> Yeah, just add it over on the right. We don't have any slash commands for it.

It doesn't seem to do anything though :cry:

**Comment by AverageMarcus** [comment]
Looks like there was a network issue with GitHub sending the webhook calls:

Screenshot 2023-09-28 at 1 56 08 pm

I re-triggered the previously failed.

**Pull request merged**
