### PR TITLE
Fix observability-bundle failing tests

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
### What this PR does

This PR increases the timeout period for observability-bundle apps from 15 to 25min. As some tests run by the CI are failing whereas all those run manually succeeded, I guess this is mainly caused by the short timeout period which doesn't give enough time for the apps to deploy. 

If this doesn't work, I'll try to add more log outputs for the tests to have a description of the apps' events.

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by AverageMarcus** [comment]
@QuantumEnigmaa Have you seen examples of it taking more than 15 minutes for the apps to be installed? I'm always resistant to just bumping the timeout as a first attempt as it will cause a delay in reporting back to people waiting for their PRs.

**Comment by QuantumEnigmaa** [comment]
> Have you seen examples of it taking more than 15 minutes for the apps to be installed?

I have seen it with some WCs creation but not as a regular thing. And for e2e testing I was never able to find the root cause before the end of the tests. :/ 

> I'm always resistant to just bumping the timeout as a first attempt as it will cause a delay in reporting back to people waiting for their PRs.

Yeah I understand that. I can first add the additional log outputs and go back to this PR if it confirms that an added delay is the way to go.

**Comment by AverageMarcus** [comment]
Lets give this PR a try for now. We can see if it improves the daily runs or not. :)

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
I think there's an issue with cert-manager (maybe rate-limiting from lets encrypt) as I'm seeing the same failing tests on other PRs. I'm going to add the skip label as this Pr is good to go.

**Comment by AverageMarcus** [comment]
@QuantumEnigmaa Feel free to merge and put out a new patch release

**Pull request merged**
