### PR TITLE
Add tests on DeploymentSets, StatefulSets and DaemonSets to ensure all desired replicas/pods are running

### PR DESCRIPTION
**Pull request by marieroque**
towards https://github.com/giantswarm/giantswarm/issues/29550

### What this PR does

Add 3 tests:
- check all DeploymentSet replicas are ready
- check all StatefulsSets replicas are ready
- check all desired daemon pods are running

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
LGTM but I'll let tinkerers chime in :)

**Review by AverageMarcus — APPROVED** [review]
Looks good to me, assuming the tests are all green :) 

Once thing I think would be worth doing eventually (not as part of this PR) is moving those helper functions into our `clustertest` module to make them more general-purpose.

**Comment by AverageMarcus** [comment]
Re-triggering the tests for the latest commit

/run cluster-test-suites

**Comment by marieroque** [comment]
@AverageMarcus 
Tests are failed
```
  {"level":"info","ts":"2024-02-08T14:33:28Z","msg":"deployment kyverno/kyverno-admission-controller has 0/3 replicas available"}
  {"level":"info","ts":"2024-02-08T14:33:39Z","msg":"deployment kyverno/kyverno-admission-controller has 0/3 replicas available"}
  [FAILED] in [It] - /app/internal/common/basic.go:78 @ 02/08/24 14:33:44.566
• [FAILED] [900.001 seconds]
Common tests basic [It] has all its Deployments Ready (means all replicas are running)
/app/internal/common/basic.go:74

  [FAILED] Timed out after 900.001s.
  Expected success, but got an error:
      <*errors.errorString | 0xc000c62450>: 
      deployment kyverno/kyverno-admission-controller has 0/3 replicas available
      {
          s: "deployment kyverno/kyverno-admission-controller has 0/3 replicas available",
      }
  In [It] at: /app/internal/common/basic.go:78 @ 02/08/24 14:33:44.566
```

Well, tests are showing issues with `kyverno-admission-controller`.

What should I do ?

**Comment by AverageMarcus** [comment]
Looks like a flake so I'm ok with skip label.

**Pull request merged**
