### PR TITLE
Add CAPA private WC tests

### PR DESCRIPTION
**Pull request by mnitchev**
### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by AverageMarcus** [comment]
The CAPZ and CAPVCD failures are [known](https://github.com/giantswarm/giantswarm/issues/29390#issuecomment-1883014984). That CAPA one looks like a flake.

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Feel free to apply the `skip/ci` label when you're ready to merge.

**Comment by mnitchev** [comment]
I added the label but it isn't approved yet. Is it time based?

**Pull request merged**
