### PR TITLE
update standup to add name for capvcd tests

### PR DESCRIPTION
**Pull request by anvddriesch**
### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by njuettner — APPROVED** [review]

**Comment by AverageMarcus** [comment]
```
  {"level":"info","ts":"2024-09-25T14:09:31Z","msg":"Cluster App status: AppVersion='', Version='', ReleaseStatus='values-schema-violation', ReleaseReason='values don't meet the specifications of the schema(s) in the following chart(s):\ncluster-cloud-director:\n- global.metadata: Additional property name is not allowed\n', LastDeployed='0001-01-01 00:00:00 +0000 UTC'"}
```

**Comment by AverageMarcus** [comment]
Has cluster-cloud-director actually been updated and released to support this change?

**Comment by vxav** [comment]
Not yet

**Comment by AverageMarcus** [comment]
So this isn't going to pass. 

What's the plan?

**Comment by vxav** [comment]
Antonia is probably working off that branch locally to have it ready

**Comment by anvddriesch** [comment]
I think we should do a vcd release today so that it will be easier to test the next batch of changes. I'll take care of it.

**Comment by anvddriesch** [comment]
vcd tests passed! I am merging this so that we can use tests for other vcd PRs

**Pull request merged**
