### PR TITLE
Re-enable CAPVCD tests on gerbil

### PR DESCRIPTION
**Pull request by glitchcrab**
towards https://github.com/giantswarm/giantswarm/issues/29581

### What this PR does

re-enables CAPVCD tests.

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Approved assuming tests pass

**Comment by yulianedyalkova** [comment]
image

**Comment by glitchcrab** [comment]
https://www.youtube.com/watch?v=pmUKmW4BYXM

/run cluster-test-suites

**Comment by glitchcrab** [comment]
ok, this test passed for CAPVCD - the only failure was for CAPV. any objections to me merging this in @giantswarm/team-tinkerers? :pray:

**Comment by glitchcrab** [comment]
yup will do

**Pull request merged**
