### PR TITLE
Re-enable capv-on-capa and capv-on-capz tests

### PR DESCRIPTION
**Pull request by glitchcrab**
towards https://github.com/giantswarm/giantswarm/issues/32054

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by glitchcrab** [comment]
yeah i screwed this - i needed https://github.com/giantswarm/giantswarm-management-clusters/pull/894

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capz/

**Comment by glitchcrab** [comment]
./run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capz/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capz/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Comment by glitchcrab** [comment]
let's try azure

/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capz/

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capz/

**Comment by glitchcrab** [comment]
ok routing is fixed for azure:

/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capz/

**Review by anvddriesch — APPROVED** [review]

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa/

**Pull request merged**
