### PR TITLE
Bumped cluster-standup-teardown to v1.25.4 to add proxy vars to CAPVCD test values

### PR DESCRIPTION
**Pull request by glitchcrab**
### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/standard,./providers/capv/on-capz,./providers/capvcd/standard,./providers/capz/private

**Comment by vxav** [comment]
Can we superseed this PR with https://github.com/giantswarm/cluster-test-suites/pull/504 (`1.25.6`) ?

**Comment by AverageMarcus** [comment]
@vxav Yes, but please copy the changelog entries from this PR into yours

**Comment by vxav** [comment]
It looks like there's a problem with the workers.
I'll be looking into it [here](https://gigantic.slack.com/archives/C01BYMF6RN0/p1728472042225279)

**Comment by AverageMarcus** [comment]
@vxav I've pulled your change into this PR so I'm going to close your PR

**Pull request merged**
