### PR TITLE
CAPZ: Change Helm values structure

### PR DESCRIPTION
**Pull request by njuettner**
### What this PR does

Towards: https://github.com/giantswarm/roadmap/issues/3371

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by tuladhar — APPROVED** [review]

**Review by AverageMarcus — APPROVED** [review]
LGTM if tests pass :)

**Review by mnitchev — APPROVED** [review]
CAPA broke on the last run but I think that's unrelated. We should merge this now as otherwise the CAPZ tests always fail

**Pull request merged**
