### PR TITLE
Added EKS autoscale tests

### PR DESCRIPTION
**Pull request by weseven**
### What this PR does
Added autoscale tests for EKS

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by weseven** [comment]
Autoscale tests went fine, waiting for the cluster-eks and default-apps-eks to be released in order to integrate last changes and update the test-suite

**Comment by weseven** [comment]
failure seems to be a fluke on CAPZ, autoscale tests work fine both in CAPA and EKS.

@giantswarm/team-tinkerers ready for review.

**Review by AverageMarcus — APPROVED** [review]

**Pull request merged**
