### PR TITLE
update cluster-standup-teardown to v1.3.0

### PR DESCRIPTION
**Pull request by glitchcrab**
### What this PR does

Updates cluster-standup-teardown to v1.3.0

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capz

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capz

**Review by AverageMarcus — APPROVED** [review]

**Pull request merged**
