### PR TITLE
Rely on CAPV default values for k8s version

### PR DESCRIPTION
**Pull request by vxav**
### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by erkanerol** [comment]
@vxav Can you change the title to state what we want to apply? e.g. "Don't overwrite default values of chart" ,"Rely on default values for k8s version"

**Comment by vxav** [comment]
> @vxav Can you change the title to state what we want to apply? e.g. "Don't overwrite default values of chart" ,"Rely on default values for k8s version"

done

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Looks like the CAPV tests are just fine with this change so I'm going to add the skip label for you.

**Comment by vxav** [comment]
For my own knowledge, how do you tell the tests are fine as it's still running?

**Comment by AverageMarcus** [comment]
Oh, I looked at the [last completed run](https://tekton.ci.giantswarm.io/#/namespaces/tekton-pipelines/pipelineruns/pr-cluster-test-suites-229-cluster-test-suites6bxvr?pipelineTask=display-results&step=display-results) I didn't see there was another still running. I'll remove the label.

**Comment by vxav** [comment]
How can I debug the failed tests?

**Comment by vxav** [comment]
It's CAPV but I suppose it's the same battle (I also get confused with my own providers)

**Comment by vxav** [comment]
Errrrr: [https://tekton.ci.giantswarm.io/#/namespaces/tekton-pipelines/pipelineruns/pr-cluster-tes[…]-229-cluster-test-suitesqcs7h-run-tests-7&step=run-tests](https://tekton.ci.giantswarm.io/#/namespaces/tekton-pipelines/pipelineruns/pr-cluster-test-suites-229-cluster-test-suitesqcs7h?pipelineTask=run-tests&taskRunName=pr-cluster-test-suites-229-cluster-test-suitesqcs7h-run-tests-7&step=run-tests)

`--- FAIL: TestCAPVCDStandard (3004.21s)`
That's a CAPV test

**Comment by AverageMarcus** [comment]
No, that's `CAPVCD` 😕

**Comment by AverageMarcus** [comment]
When making changes to `cluster-test-suites` itself it does. All other repos it only runs the specific provider tests.

**Pull request merged**
