### PR TITLE
Switched to using dns and http clients from clustertest

### PR DESCRIPTION
**Pull request by AverageMarcus**
### What this PR does

Fixes https://github.com/giantswarm/giantswarm/issues/31135

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by ericgraf — APPROVED** [review]

**Review by fiunchinho — APPROVED** [review]

**Comment by AverageMarcus** [comment]
🤔  Looks like I broke the http client. Maybe it using the resolver isn't right. I'll do some more testing.

**Comment by AverageMarcus** [comment]
Looks like CAPA China is playing up today but other test suites are passing ok so I'm going to add the skip label.

**Pull request merged**
