### PR TITLE
Increase char count of clusters to 20 chars

### PR DESCRIPTION
**Pull request by AverageMarcus**
### What this PR does

- Fixes https://github.com/giantswarm/giantswarm/issues/28901

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by ericgraf — APPROVED** [review]

**Comment by AverageMarcus** [comment]
😡 The tests keep failing at different points for seemingly unrelated reasons. I'm not sure what the problem is.

/run cluster-test-suites

**Pull request merged**
