### PR TITLE
Wait for Org to finish deleting

### PR DESCRIPTION
**Pull request by AverageMarcus**
### What this PR does

- Ensures the tests wait for the Org to be fully deleted before completing (by updating `clustertest` to v0.0.11)
- Adds a PR template to ensure the E2E tests are triggered for each PR
- Calls to `IsNumNodesReady` changed to `AreNumNodesReady` as the function name changed in the `clustertest` module.
- Increased Ginkgo test suite timeout to 4 hour
- Enable remaining test suites to continue running when one fails

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by calvix** [comment]
I am a little bit confused about how a function called `AreNumNodesReady` has anything to do with the organization being deleted.

**Comment by AverageMarcus** [comment]
@calvix The function name changed between versions. It was actually going to be part of https://github.com/giantswarm/cluster-test-suites/pull/19 but that's taking longer than expected :( 

I'll add a note to the description about it.

**Review by calvix — COMMENTED** [review]
still confused as i don't see any change that would do anything with organization deletion, but i will trust you

**Review by calvix — APPROVED** [review]

**Comment by AverageMarcus** [comment]
The change comes from updating of `clustertest` to v0.0.11 - https://github.com/giantswarm/clustertest/blob/main/CHANGELOG.md#0011---2023-05-11

**Pull request merged**
