### PR TITLE
Generate test result reports for each test suite

### PR DESCRIPTION
**Pull request by AverageMarcus**
### What this PR does

Generates test result files that can be used to display the overall results when running suites in parallel. 

Towards: https://github.com/giantswarm/giantswarm/issues/26717
Linked with: https://github.com/giantswarm/tekton-resources/pull/121

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Retesting now `grizzly` should be fixed.

/run cluster-test-suites

**Review by yulianedyalkova — APPROVED** [review]

**Review by ericgraf — APPROVED** [review]

**Pull request merged**
