### PR TITLE
Re-enable `capa-private` tests because EC2 user data limit issue should be solved now that we store Ignition bootstrap data in S3

### PR DESCRIPTION
**Pull request by AndiDog**
### What this PR does

https://github.com/giantswarm/roadmap/issues/3442 should've fixed this. See https://github.com/giantswarm/roadmap/issues/3442.

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

(done via comment, see below)

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Triggering the tests just for the re-enabled test suite: 

/run cluster-test-suites TARGET_SUITES=./providers/capa/private

**Review by AverageMarcus — APPROVED** [review]

**Review by fiunchinho — APPROVED** [review]

**Comment by AverageMarcus** [comment]
The cluster failed to delete because the `aws-vpc-operator` crashed with:

```
2024-07-15T09:50:18.499Z        ERROR   Reconciler error        {"controller": "awscluster", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "AWSCluster", "AWSCluster": {"name":"t-b0r9t061akd1lzbl0j","namespace":"org-t-ufytg52gq3ae88gewn"}, "namespace": "org-t-ufytg52gq3ae88gewn", "name": "t-b0r9t061akd1lzbl0j", "reconcileID": "34e27e51-c8be-4a95-a96c-509d8b3bca62", "error": "AWSCluster.infrastructure.cluster.x-k8s.io \"t-b0r9t061akd1lzbl0j\" is invalid: spec.network.subnets[1]: Duplicate value: map[string]interface {}{\"id\":\"\"}", "errorCauses": [{"error": "AWSCluster.infrastructure.cluster.x-k8s.io \"t-b0r9t061akd1lzbl0j\" is invalid: spec.network.subnets[1]: Duplicate value: map[string]interface {}{\"id\":\"\"}"}]}
```

**Comment by AndiDog** [comment]
We first have to fix `aws-vpc-operator`. It's failing since we upgraded the CRD, very likely because it doesn't fill `AWSCluster.spec.subnets[*].resourceID` correctly. I also don't see much more need for the complicated recon logic of subnets in that operator – CAPA can hopefully do whatever is needed.

**Comment by AndiDog** [comment]
Private cluster tests worked fine, but unrelated suites failed. I'm therefore merging this change.

**Pull request merged**
